services:
  - type: web
    name: my-fastapi-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload
    pythonVersion: 3.11
